/*    ==Scripting Parameters==

    Source Server Version : SQL Server 2016 (13.0.4001)
    Source Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Source Database Engine Type : Standalone SQL Server

    Target Server Version : SQL Server 2016
    Target Database Engine Edition : Microsoft SQL Server Enterprise Edition
    Target Database Engine Type : Standalone SQL Server
*/

USE [master]
GO

/****** Object:  Database [PaymentGateway]    Script Date: 14/07/2019 19:00:05 ******/
CREATE DATABASE [PaymentGateway]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PaymentGateway', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQL2016DE\MSSQL\DATA\PaymentGateway.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PaymentGateway_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQL2016DE\MSSQL\DATA\PaymentGateway_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [PaymentGateway] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PaymentGateway].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PaymentGateway] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PaymentGateway] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PaymentGateway] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PaymentGateway] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PaymentGateway] SET ARITHABORT OFF 
GO

ALTER DATABASE [PaymentGateway] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PaymentGateway] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PaymentGateway] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PaymentGateway] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PaymentGateway] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PaymentGateway] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PaymentGateway] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PaymentGateway] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PaymentGateway] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PaymentGateway] SET  ENABLE_BROKER 
GO

ALTER DATABASE [PaymentGateway] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PaymentGateway] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PaymentGateway] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PaymentGateway] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PaymentGateway] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PaymentGateway] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [PaymentGateway] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PaymentGateway] SET RECOVERY FULL 
GO

ALTER DATABASE [PaymentGateway] SET  MULTI_USER 
GO

ALTER DATABASE [PaymentGateway] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PaymentGateway] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PaymentGateway] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PaymentGateway] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PaymentGateway] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PaymentGateway] SET QUERY_STORE = OFF
GO

USE [PaymentGateway]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [PaymentGateway] SET  READ_WRITE 
GO


