// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PaymentGateway.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PaymentRequest
    {
        /// <summary>
        /// Initializes a new instance of the PaymentRequest class.
        /// </summary>
        public PaymentRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PaymentRequest class.
        /// </summary>
        public PaymentRequest(string id = default(string), double? amount = default(double?), string currency = default(string), string merchantId = default(string), System.DateTime? createdDate = default(System.DateTime?), Card card = default(Card))
        {
            Id = id;
            Amount = amount;
            Currency = currency;
            MerchantId = merchantId;
            CreatedDate = createdDate;
            Card = card;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "amount")]
        public double? Amount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "currency")]
        public string Currency { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "merchantId")]
        public string MerchantId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "createdDate")]
        public System.DateTime? CreatedDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "card")]
        public Card Card { get; set; }

    }
}
